import "../globals.css";
export const metadata = {
  title: 'Home',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <h1>Home Layout</h1>
      <body>{children}</body>
    </html>
  )
}
