export const metadata = {
  title: 'Dashboard',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,expenses, notifications, revenue, login
}: {
  children: React.ReactNode,
  expenses: React.ReactNode,
  notifications: React.ReactNode,
  revenue: React.ReactNode,
  login: React.ReactNode,
}) {
  const isLoggedIn = true;
  
  return isLoggedIn ? (
    <html>
      <body>
        <div>{children}</div>
        <div>{expenses}</div>
        <div>{notifications}</div>
        <div>{revenue}</div>
      </body>
    </html>
  ) : (
    <html>
      <body>
        <div>{login}</div>
      </body>
    </html>
  );
}
