import type { Metadata } from "next";
import "../../globals.css";
export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <h1>Dashboard Layout</h1>
        {children}
      </body>
    </html>
  );
}
