import type { Metadata } from "next";
import Navbar from "../components/Navbar";

export const metadata: Metadata = {
  title: "Shop",
  description: "Generated by create next app",
};

export default function ProductLayout ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return(
    <>
    <Navbar/>
     <body>
          {children}
    </body>
    </>
  )
}