import type { Metadata } from "next";
import '../globals.css'

export const metadata: Metadata = {
  title: "products",
  description: "Generated by create next app",
};

export default function ProductLayout ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return(
    <html lang="en">
     <body>
          {children}
    </body>
    </html>
  )
}